INSERT INTO countries VALUES (1,'AF','AFG','Afghanistan');
INSERT INTO countries VALUES (2,'AL','ALB','Albania');
INSERT INTO countries VALUES (3,'DZ','DZA','Algeria');
INSERT INTO countries VALUES (4,'AS','ASM','American Samoa');
INSERT INTO countries VALUES (5,'AD','AND','Andorra');
INSERT INTO countries VALUES (6,'AO','AGO','Angola');
INSERT INTO countries VALUES (7,'AI','AIA','Anguilla');
INSERT INTO countries VALUES (8,'AR','ARG','Argentina');
INSERT INTO countries VALUES (9,'AA',NULL,'Armenia');
INSERT INTO countries VALUES (10,'AW','ABW','Aruba');
INSERT INTO countries VALUES (11,'AU','AUS','Australia');
INSERT INTO countries VALUES (12,'AT','AUT','Austria');
INSERT INTO countries VALUES (13,'AZ','AZE','Azerbaijan');
INSERT INTO countries VALUES (14,'BS','BHS','Bahamas');
INSERT INTO countries VALUES (15,'BH','BHR','Bahrain');
INSERT INTO countries VALUES (16,'BD','BGD','Bangladesh');
INSERT INTO countries VALUES (17,'BB','BRB','Barbados');
INSERT INTO countries VALUES (18,'BY','BLR','Belarus');
INSERT INTO countries VALUES (19,'BE','BEL','Belgium');
INSERT INTO countries VALUES (20,'BZ','BLZ','Belize');
INSERT INTO countries VALUES (21,'BJ','BEN','Benin');
INSERT INTO countries VALUES (22,'BM','BMU','Bermuda');
INSERT INTO countries VALUES (23,'BT','BTN','Bhutan');
INSERT INTO countries VALUES (24,'BO','BOL','Bolivia');
INSERT INTO countries VALUES (26,'BA','BIH','Bosnia &amp; Herzegovina');
INSERT INTO countries VALUES (27,'BW','BWA','Botswana');
INSERT INTO countries VALUES (28,'BR','BRA','Brazil');
INSERT INTO countries VALUES (29,'BC',NULL,'British Indian Ocean Ter');
INSERT INTO countries VALUES (30,'BN','BRN','Brunei');
INSERT INTO countries VALUES (31,'BG','BGR','Bulgaria');
INSERT INTO countries VALUES (32,'BF','BFA','Burkina Faso');
INSERT INTO countries VALUES (33,'BI','BDI','Burundi');
INSERT INTO countries VALUES (34,'KH','KHM','Cambodia');
INSERT INTO countries VALUES (35,'CM','CMR','Cameroon');
INSERT INTO countries VALUES (36,'CA','CAN','Canada');
INSERT INTO countries VALUES (37,'IC',NULL,'Canary Islands');
INSERT INTO countries VALUES (38,'CV','CPV','Cape Verde');
INSERT INTO countries VALUES (39,'KY','CYM','Cayman Islands');
INSERT INTO countries VALUES (40,'CF','CAF','Central African Republic');
INSERT INTO countries VALUES (41,'TD','TCD','Chad');
INSERT INTO countries VALUES (42,NULL,NULL,'Channel Islands');
INSERT INTO countries VALUES (43,'CL','CHL','Chile');
INSERT INTO countries VALUES (44,'CN','CHN','China');
INSERT INTO countries VALUES (45,'CI','CIV','Christmas Island');
INSERT INTO countries VALUES (46,'CS',NULL,'Cocos Island');
INSERT INTO countries VALUES (47,'CO','COL','Colombia');
INSERT INTO countries VALUES (48,'CC','CCK','Comoros');
INSERT INTO countries VALUES (49,'CG','COG','Congo');
INSERT INTO countries VALUES (50,'CK','COK','Cook Islands');
INSERT INTO countries VALUES (51,'CR','CRI','Costa Rica');
INSERT INTO countries VALUES (52,'CT',NULL,'Cote D\'Ivoire');
INSERT INTO countries VALUES (53,'HR','HRV','Croatia');
INSERT INTO countries VALUES (54,'CU','CUB','Cuba');
INSERT INTO countries VALUES (55,'CB',NULL,'Curacao');
INSERT INTO countries VALUES (56,'CY','CYP','Cyprus');
INSERT INTO countries VALUES (57,'CZ','CZE','Czech Republic');
INSERT INTO countries VALUES (58,'DK','DNK','Denmark');
INSERT INTO countries VALUES (59,'DJ','DJI','Djibouti');
INSERT INTO countries VALUES (60,'DM','DMA','Dominica');
INSERT INTO countries VALUES (61,'DO','DOM','Dominican Republic');
INSERT INTO countries VALUES (62,'TM','TKM','East Timor');
INSERT INTO countries VALUES (63,'EC','ECU','Ecuador');
INSERT INTO countries VALUES (64,'EG','EGY','Egypt');
INSERT INTO countries VALUES (65,'SV','SLV','El Salvador');
INSERT INTO countries VALUES (66,'GQ','GNQ','Equatorial Guinea');
INSERT INTO countries VALUES (67,'ER','ERI','Eritrea');
INSERT INTO countries VALUES (68,'EE','EST','Estonia');
INSERT INTO countries VALUES (69,'ET','ETH','Ethiopia');
INSERT INTO countries VALUES (70,'FA',NULL,'Falkland Islands');
INSERT INTO countries VALUES (71,'FO','FRO','Faroe Islands');
INSERT INTO countries VALUES (72,'FJ','FJI','Fiji');
INSERT INTO countries VALUES (73,'FI','FIN','Finland');
INSERT INTO countries VALUES (74,'FR','FRA','France');
INSERT INTO countries VALUES (75,'GF','GUF','French Guiana');
INSERT INTO countries VALUES (76,'PF','PYF','French Polynesia');
INSERT INTO countries VALUES (77,'FS',NULL,'French Southern Ter');
INSERT INTO countries VALUES (78,'GA','GAB','Gabon');
INSERT INTO countries VALUES (79,'GM','GMB','Gambia');
INSERT INTO countries VALUES (80,'GE','GEO','Georgia');
INSERT INTO countries VALUES (81,'DE','DEU','Germany');
INSERT INTO countries VALUES (82,'GH','GHA','Ghana');
INSERT INTO countries VALUES (83,'GI','GIB','Gibraltar');
INSERT INTO countries VALUES (84,'GR','GRC','Greece');
INSERT INTO countries VALUES (85,'GL','GRL','Greenland');
INSERT INTO countries VALUES (86,'GD','GRD','Grenada');
INSERT INTO countries VALUES (87,'GP','GLP','Guadeloupe');
INSERT INTO countries VALUES (88,'GU','GUM','Guam');
INSERT INTO countries VALUES (89,'GT','GTM','Guatemala');
INSERT INTO countries VALUES (90,'GN','GIN','Guinea');
INSERT INTO countries VALUES (91,'GY','GUY','Guyana');
INSERT INTO countries VALUES (92,'HT','HTI','Haiti');
INSERT INTO countries VALUES (93,'HW',NULL,'Hawaii');
INSERT INTO countries VALUES (94,'HN','HND','Honduras');
INSERT INTO countries VALUES (95,'HK','HKG','Hong Kong');
INSERT INTO countries VALUES (96,'HU','HUN','Hungary');
INSERT INTO countries VALUES (97,'IS','ISL','Iceland');
INSERT INTO countries VALUES (98,'IN','IND','India');
INSERT INTO countries VALUES (99,'ID','IDN','Indonesia');
INSERT INTO countries VALUES (100,'IA',NULL,'Iran');
INSERT INTO countries VALUES (101,'IQ','IRQ','Iraq');
INSERT INTO countries VALUES (102,'IE','IRL','Ireland');
INSERT INTO countries VALUES (103,'IM','IMN','Isle of Man');
INSERT INTO countries VALUES (104,'IL','ISR','Israel');
INSERT INTO countries VALUES (105,'IT','ITA','Italy');
INSERT INTO countries VALUES (106,'JM','JAM','Jamaica');
INSERT INTO countries VALUES (107,'JP','JPN','Japan');
INSERT INTO countries VALUES (108,'JO','JOR','Jordan');
INSERT INTO countries VALUES (109,'KZ','KAZ','Kazakhstan');
INSERT INTO countries VALUES (110,'KE','KEN','Kenya');
INSERT INTO countries VALUES (111,'KI','KIR','Kiribati');
INSERT INTO countries VALUES (112,'NK',NULL,'Korea North');
INSERT INTO countries VALUES (113,'KR','KOR','South Korea');
INSERT INTO countries VALUES (114,'KW','KWT','Kuwait');
INSERT INTO countries VALUES (115,'KG','KGZ','Kyrgyzstan');
INSERT INTO countries VALUES (116,'LA','LAO','Laos');
INSERT INTO countries VALUES (117,'LV','LVA','Latvia');
INSERT INTO countries VALUES (118,'LB','LBN','Lebanon');
INSERT INTO countries VALUES (119,'LS','LSO','Lesotho');
INSERT INTO countries VALUES (120,'LR','LBR','Liberia');
INSERT INTO countries VALUES (121,'LY','LBY','Libya');
INSERT INTO countries VALUES (122,'LI','LIE','Liechtenstein');
INSERT INTO countries VALUES (123,'LT','LTU','Lithuania');
INSERT INTO countries VALUES (124,'LU','LUX','Luxembourg');
INSERT INTO countries VALUES (125,'MO','MAC','Macau');
INSERT INTO countries VALUES (126,'MK','MKD','Macedonia');
INSERT INTO countries VALUES (127,'MG','MDG','Madagascar');
INSERT INTO countries VALUES (128,'MY','MYS','Malaysia');
INSERT INTO countries VALUES (129,'MW','MWI','Malawi');
INSERT INTO countries VALUES (130,'MV','MDV','Maldives');
INSERT INTO countries VALUES (131,'ML','MLI','Mali');
INSERT INTO countries VALUES (132,'MT','MLT','Malta');
INSERT INTO countries VALUES (133,'MH','MHL','Marshall Islands');
INSERT INTO countries VALUES (134,'MQ','MTQ','Martinique');
INSERT INTO countries VALUES (135,'MR','MRT','Mauritania');
INSERT INTO countries VALUES (136,'MU','MUS','Mauritius');
INSERT INTO countries VALUES (137,'MX','MEX','Mexico');
INSERT INTO countries VALUES (138,'MI',NULL,'Midway Islands');
INSERT INTO countries VALUES (139,'MD','MDA','Moldova');
INSERT INTO countries VALUES (140,'MC','MCO','Monaco');
INSERT INTO countries VALUES (141,'MN','MNG','Mongolia');
INSERT INTO countries VALUES (142,'MS','MSR','Montserrat');
INSERT INTO countries VALUES (143,'MA','MAR','Morocco');
INSERT INTO countries VALUES (144,'MZ','MOZ','Mozambique');
INSERT INTO countries VALUES (145,'MM','MMR','Myanmar');
INSERT INTO countries VALUES (146,'NA','NAM','Namibia');
INSERT INTO countries VALUES (147,'NU','NIU','Nauru');
INSERT INTO countries VALUES (148,'NP','NPL','Nepal');
INSERT INTO countries VALUES (149,'AN','ANT','Netherland Antilles');
INSERT INTO countries VALUES (150,'NL','NLD','Netherlands (Holland, Europe)');
INSERT INTO countries VALUES (151,'NV',NULL,'Nevis');
INSERT INTO countries VALUES (152,'NC','NCL','New Caledonia');
INSERT INTO countries VALUES (153,'NZ','NZL','New Zealand');
INSERT INTO countries VALUES (154,'NI','NIC','Nicaragua');
INSERT INTO countries VALUES (155,'NE','NER','Niger');
INSERT INTO countries VALUES (156,'NG','NGA','Nigeria');
INSERT INTO countries VALUES (157,'NW',NULL,'Niue');
INSERT INTO countries VALUES (158,'NF','NFK','Norfolk Island');
INSERT INTO countries VALUES (159,'NO','NOR','Norway');
INSERT INTO countries VALUES (160,'OM','OMN','Oman');
INSERT INTO countries VALUES (161,'PK','PAK','Pakistan');
INSERT INTO countries VALUES (162,'PW','PLW','Palau Island');
INSERT INTO countries VALUES (163,'PS','PSE','Palestine');
INSERT INTO countries VALUES (164,'PA','PAN','Panama');
INSERT INTO countries VALUES (165,'PG','PNG','Papua New Guinea');
INSERT INTO countries VALUES (166,'PY','PRY','Paraguay');
INSERT INTO countries VALUES (167,'PE','PER','Peru');
INSERT INTO countries VALUES (168,'PH','PHL','Philippines');
INSERT INTO countries VALUES (169,'PO',NULL,'Pitcairn Island');
INSERT INTO countries VALUES (170,'PL','POL','Poland');
INSERT INTO countries VALUES (171,'PT','PRT','Portugal');
INSERT INTO countries VALUES (172,'PR','PRI','Puerto Rico');
INSERT INTO countries VALUES (173,'QA','QAT','Qatar');
INSERT INTO countries VALUES (174,'ME','MNE','Republic of Montenegro');
INSERT INTO countries VALUES (175,'RS','SRB','Republic of Serbia');
INSERT INTO countries VALUES (176,'RE','REU','Reunion');
INSERT INTO countries VALUES (177,'RO','ROU','Romania');
INSERT INTO countries VALUES (178,'RU','RUS','Russia');
INSERT INTO countries VALUES (179,'RW','RWA','Rwanda');
INSERT INTO countries VALUES (180,'BL','BLM','St Barthelemy');
INSERT INTO countries VALUES (181,'BQ','BES','Bonaire, Sint Eustatius and Saba');
INSERT INTO countries VALUES (182,'HE',NULL,'St Helena');
INSERT INTO countries VALUES (183,'KN','KNA','St Kitts-Nevis');
INSERT INTO countries VALUES (184,'LC','LCA','St Lucia');
INSERT INTO countries VALUES (185,'SX','SXM','Sint Maarten');
INSERT INTO countries VALUES (186,'PM','SPM','St Pierre &amp; Miquelon');
INSERT INTO countries VALUES (187,'VC','VCT','St Vincent &amp; Grenadines');
INSERT INTO countries VALUES (188,'SP',NULL,'Saipan');
INSERT INTO countries VALUES (189,'WS','WSM','Samoa');
INSERT INTO countries VALUES (190,'SM','SMR','San Marino');
INSERT INTO countries VALUES (191,'ST','STP','Sao Tome &amp; Principe');
INSERT INTO countries VALUES (192,'SA','SAU','Saudi Arabia');
INSERT INTO countries VALUES (193,'SN','SEN','Senegal');
INSERT INTO countries VALUES (194,'SC','SYC','Seychelles');
INSERT INTO countries VALUES (195,'SL','SLE','Sierra Leone');
INSERT INTO countries VALUES (196,'SG','SGP','Singapore');
INSERT INTO countries VALUES (197,'SK','SVK','Slovakia');
INSERT INTO countries VALUES (198,'SI','SVN','Slovenia');
INSERT INTO countries VALUES (199,'SB','SLB','Solomon Islands');
INSERT INTO countries VALUES (200,'SO','SOM','Somalia');
INSERT INTO countries VALUES (201,'ZA','ZAF','South Africa');
INSERT INTO countries VALUES (202,'ES','ESP','Spain');
INSERT INTO countries VALUES (203,'LK','LKA','Sri Lanka');
INSERT INTO countries VALUES (204,'SD','SDN','Sudan');
INSERT INTO countries VALUES (205,'SR','SUR','Suriname');
INSERT INTO countries VALUES (206,'SZ','SWZ','Swaziland');
INSERT INTO countries VALUES (207,'SE','SWE','Sweden');
INSERT INTO countries VALUES (208,'CH','CHE','Switzerland');
INSERT INTO countries VALUES (209,'SY','SYR','Syria');
INSERT INTO countries VALUES (210,'TA',NULL,'Tahiti');
INSERT INTO countries VALUES (211,'TW','TWN','Taiwan');
INSERT INTO countries VALUES (212,'TJ','TJK','Tajikistan');
INSERT INTO countries VALUES (213,'TZ','TZA','Tanzania');
INSERT INTO countries VALUES (214,'TH','THA','Thailand');
INSERT INTO countries VALUES (215,'TG','TGO','Togo');
INSERT INTO countries VALUES (216,'TK','TKL','Tokelau');
INSERT INTO countries VALUES (217,'TO','TON','Tonga');
INSERT INTO countries VALUES (218,'TT','TTO','Trinidad &amp; Tobago');
INSERT INTO countries VALUES (219,'TN','TUN','Tunisia');
INSERT INTO countries VALUES (220,'TR','TUR','Turkey');
INSERT INTO countries VALUES (221,'TU',NULL,'Turkmenistan');
INSERT INTO countries VALUES (222,'TC','TCA','Turks &amp; Caicos Is');
INSERT INTO countries VALUES (223,'TV','TUV','Tuvalu');
INSERT INTO countries VALUES (224,'UG','UGA','Uganda');
INSERT INTO countries VALUES (225,'UA','UKR','Ukraine');
INSERT INTO countries VALUES (226,'AE','ARE','United Arab Emirates');
INSERT INTO countries VALUES (227,'GB','GBR','United Kingdom');
INSERT INTO countries VALUES (228,'US','USA','United States');
INSERT INTO countries VALUES (229,'UY','URY','Uruguay');
INSERT INTO countries VALUES (230,'UZ','UZB','Uzbekistan');
INSERT INTO countries VALUES (231,'VU','VUT','Vanuatu');
INSERT INTO countries VALUES (232,'VA','VAT','Vatican City State');
INSERT INTO countries VALUES (233,'VE','VEN','Venezuela');
INSERT INTO countries VALUES (234,'VN','VNM','Vietnam');
INSERT INTO countries VALUES (235,'VG','VGB','British Virgin Islands');
INSERT INTO countries VALUES (236,'VI','VIR','US Virgin Islands');
INSERT INTO countries VALUES (237,'WK',NULL,'Wake Island');
INSERT INTO countries VALUES (238,'WF','WLF','Wallis &amp; Futana Is');
INSERT INTO countries VALUES (239,'YE','YEM','Yemen');
INSERT INTO countries VALUES (240,'ZR',NULL,'Zaire');
INSERT INTO countries VALUES (241,'ZM','ZMB','Zambia');
INSERT INTO countries VALUES (242,'ZW','ZWE','Zimbabwe');
INSERT INTO countries VALUES (25,'AG','ATG','Antigua and Barbuda');
INSERT INTO countries VALUES (243,'CD','COD','Democtratic Republic of the Congo');
INSERT INTO countries VALUES (244,'SS','SSD','South Sudan');
INSERT INTO countries VALUES (245,'GW','GNB','Guinea-Bissau');
INSERT INTO countries VALUES (246,'YT','MYT','Mayotte');
INSERT INTO countries VALUES (247,'EH','ESH','Western Sahara');
